const data = {
    products: [
        {
            _id: '7',
            name: 'Onion hair Oil',
            category: 'Hair Products',
            image: '/images/p1.jpg',
            price: 520,
            countInStock: 10,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product hair oil',
        },
        {
            _id: '8',
            name: 'Onion Shappoo',
            category: 'Shappoo',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'MamaEarth',
            rating: 4.0,
            numReviews: 10,
            description: 'Onion Shampoo with Onion and Plant Keratin',
        },
        {
            _id: '9',
            name: 'Face Wash',
            category: 'Face Wash',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 10,
            brand: 'MamaEarth',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality Face Wash',
        },
        {
            _id: '10',
            name: 'Anti-Hair Fall Kit',
            category: 'Hair Care',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 14,
            description: 'Anti-Hair Fall Kit for Hair Care',
        },
        {
            _id: '11',
            name: 'Body Care Kit',
            category: 'Skin care',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 15,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 10,
            description: 'Body Care Kit for - Body Lotion 400ml',
        },
        {
            _id: '12',
            name: 'Baby Essential Kit',
            category: 'baby Products',
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 15,
            description: 'Baby Essential Kit For babies',
        },
        {
            _id: '13',
            name: 'Hair oil',
            category: 'Hair Care',
            image: '/images/p44.jpg',
            price: 78,
            countInStock: 15,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 14,
            description: 'Hair oil for Regrowth 250ml',
        },
        {
            _id: '14',
            name: 'Hair Conditioner',
            category: 'Hair Care',
            image: '/images/p55.jpg',
            price: 65,
            countInStock: 15,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 10,
            description: 'Hair Conditioner for Hair Care',
        },
        {
            _id: '15',
            name: 'Onion Hair Serum',
            category: 'Hair Care',
            image: '/images/p66.jpg',
            price: 139,
            countInStock: 12,
            brand: 'MamaEarth',
            rating: 4.5,
            numReviews: 15,
            description: 'Onion Hair Serum with Onion and Biotin 250ml',
        },
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p14.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p15.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p16.jpg',
            price: 220,
            countInStock: 10,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p10.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p11.jpg',
            price: 65,
            countInStock: 15,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p12.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
export default data;